name: CI
on: [push]

jobs:
  checkRunCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check contains [ci:]
        run: echo checkRunCI.

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
