name: CI
on: [push]

jobs:
  checkRunCi:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci:')"
    steps:
      - uses: actions/checkout@v2
      - name: Run check contains [ci:]
        run: echo checkRunCi.

  build:
    needs: checkRunCi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
